site_name: TKJHAT Micropython API

nav:
  - Home: index.md
  - About: about.md
  - Tatu: Tatu.md
  - Alisa: Alisa.md
  - Aleksanteri: Aleksanteri.md
  - Sensors:
      - Sensor Overview: Sensors/sensor_overview.md
      - Temp & Humi - HDC2021: Sensors/hdc2021.md
      - Buzzer:  Sensors/buzzer.md
      - Buttons:  Sensors/buttons.md
      - Led: Sensors/led.md
      - RGB Led:  Sensors/rgb_led.md
      - Ambient Light - VEML6030: Sensors/veml6030.md
      - Gyro - ICM42670: Sensors/icm42670.md
      - Display - SSD1306: Sensors/display.md
theme: readthedocs
